# とりあえず使いたい場合はこっち gem の設定も

#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_bin
  pool: 5
  timeout: 5000
  database: gfdmskill 
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: sqale_64dd2d130f
  host: mysql001.sqale.jp
